class COMMAND:
    CMD_MOTOR = "CMD_MOTOR"
    CMD_M_MOTOR = "CMD_M_MOTOR"
    CMD_CAR_ROTATE = "CMD_CAR_ROTATE"
    CMD_LED = "CMD_LED"
    CMD_LED_MOD = "CMD_LED_MOD"
    CMD_SERVO = "CMD_SERVO"
    CMD_BUZZER = "CMD_BUZZER"
    CMD_SONIC = "CMD_SONIC"
    CMD_LIGHT = "CMD_LIGHT"
    CMD_POWER = "CMD_POWER" 
    CMD_MODE ="CMD_MODE"
    CMD_SENSOR = "CMD_SENSOR"
    CMD_BOUNDARY = "CMD_BOUNDARY#"
    def __init__(self):
        pass
